# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
production:
    MAIL_GMAIL: "instrumentados@gmail.com"
    PASSWORD_GMAIL: "mastersofcodin"
    FACEBOOK_KEY: "1961385167474682"
    FACEBOOK_SECRET: "db369f6364604df589b0968c2d937ddb"
    GOOGLE_KEY: "691425272482-2qu7lr9s9j9epo3r5stcj7kqdcnue2be.apps.googleusercontent.com"
    GOOGLE_SECRET: "9EuUejXsJfooKpDYO02jv_Rt"
development:
    MAIL_GMAIL: "instrumentados@gmail.com"
    PASSWORD_GMAIL: "mastersofcodin"
    FACEBOOK_KEY: "1961385167474682"
    FACEBOOK_SECRET: "db369f6364604df589b0968c2d937ddb"
    GOOGLE_KEY: "691425272482-2qu7lr9s9j9epo3r5stcj7kqdcnue2be.apps.googleusercontent.com"
    GOOGLE_SECRET: "9EuUejXsJfooKpDYO02jv_Rt"
