# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e99844727724cd326bea1586f03d38275a04f66668e3f49db1f0278adda3788eb83b94d81968f560f495dbfc35ef91fd0794ed571065c7a4e4f675466e72ef0f

test:
  secret_key_base: cd2e26d3d81d00a6b93d5e4f973e600170013caec1200eed9d8bcce4acab6a7eeb228038903ca3cc6c45a057935955a91e2b5391e6995f7bdd2c881dcf59c5ba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
